import React from "react";
import Head from "next/head";
import Header from "../components/Header";
import AboutPage from "../components/AboutPage";
import Footer from "../components/Footer";

const About = () => {
  return (
    <>
      <Head>
        <title>Coffee Roasters</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/favicon.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Barlow:wght@400;700&family=Fraunces:opsz,wght@9..144,400;9..144,900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <div className="container">
        <Header />
        <AboutPage />
        <Footer />
      </div>
    </>
  );
};

export default About;
