import Head from "next/head";
import Header from "../components/Header";
import LandingPage from "../components/LandingPage";

export default function Home() {
  return (
    <>
      <Head>
        <title>Coffee Roasters</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/assets/favicon.png" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=Barlow:wght@400;700&family=Fraunces:opsz,wght@9..144,400;9..144,900&display=swap"
          rel="stylesheet"
        />
      </Head>
      <Header />
      <LandingPage />
    </>
  );
}
